package com.example.data.model

enum class UserRole {
    SHOPKEEPER,
    CUSTOMER
}

typealias AppMode = UserRole

enum class ThemeMode {
    LIGHT,
    DARK,
    SYSTEM
}

enum class ShopkeeperTab {
    HOME,
    CUSTOMERS,
    REQUESTS,
    NOTIFICATIONS,
    SETTINGS
}

enum class CustomerTab {
    HOME,
    KHATA,
    PAYMENTS,
    NOTIFICATIONS,
    SETTINGS
}

enum class PaymentStatus {
    PENDING,
    ACCEPTED,
    REJECTED
}

data class UserProfile(
    val uid: String,
    val role: UserRole,
    val name: String,
    val email: String,
    val shopName: String? = null,
    val khataNumber: String? = null,
    val phone: String = "",
    val createdAt: Long = System.currentTimeMillis()
)

data class Customer(
    val id: String,
    val shopkeeperUid: String = "",
    val khataNumber: String,
    val name: String,
    val phone: String = "",
    val address: String = "",
    val linkedCustomerUid: String? = null,
    val createdAt: Long = System.currentTimeMillis()
)

/**
 * Represents a connection between a Customer's account and a Shopkeeper's khata.
 * Stored in users/{customerUid}/connectedKhatas/{connectionId}.
 * Does NOT duplicate transactions; references the shopkeeper's authorized khata.
 */
data class ConnectedKhata(
    val connectionId: String,
    val customerUid: String,
    val shopId: String,
    val shopName: String,
    val shopOwnerName: String = "",
    val customerId: String,
    val khataNumber: String,
    val customerName: String = "",
    val connectedAt: Long = System.currentTimeMillis(),
    val status: String = "ACTIVE"
)

/**
 * Temporary QR linking session generated by a shopkeeper to let a customer link their khata.
 * Financial details, passwords, and private data are intentionally excluded.
 */
data class QrLinkingSession(
    val token: String,
    val shopId: String,
    val shopName: String,
    val shopOwnerName: String = "",
    val customerId: String,
    val customerName: String,
    val khataNumber: String,
    val createdAt: Long = System.currentTimeMillis(),
    val expiresAt: Long = System.currentTimeMillis() + (15 * 60 * 1000L), // 15 minutes validity
    val isUsed: Boolean = false,
    val usedByUid: String? = null
) {
    val isExpired: Boolean
        get() = System.currentTimeMillis() > expiresAt
}

/**
 * Verified metadata returned after scanning a valid shopkeeper QR code.
 */
data class QrLinkVerificationResult(
    val token: String,
    val shopId: String,
    val shopName: String,
    val shopOwnerName: String,
    val customerId: String,
    val customerName: String,
    val khataNumber: String
)

data class KhataItem(
    val id: String,
    val customerId: String,
    val shopkeeperUid: String = "",
    val monthKey: String, // e.g. "2026-10"
    val date: String,     // e.g. "01 Oct 2026"
    val name: String,     // e.g. "Rice"
    val price: Double,    // e.g. 2000.0
    val createdAt: Long = System.currentTimeMillis()
)

data class MonthlyKhataRecord(
    val id: String = "",
    val customerId: String,
    val shopkeeperUid: String = "",
    val monthKey: String,     // "2026-09"
    val monthLabel: String,   // "September 2026"
    val totalPurchases: Double,
    val paidAmount: Double,
    val isCurrentActiveMonth: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
) {
    val remainingBalance: Double
        get() = (totalPurchases - paidAmount).coerceAtLeast(0.0)

    val status: String
        get() = when {
            isCurrentActiveMonth -> "Active"
            remainingBalance <= 0.0 -> "Paid"
            paidAmount > 0.0 -> "Partially Paid"
            else -> "Unpaid"
        }
}

data class PaymentRequest(
    val id: String,
    val shopkeeperUid: String = "",
    val shopName: String = "",
    val customerUid: String = "",
    val customerId: String,
    val customerName: String,
    val khataNumber: String,
    val targetMonthLabel: String,
    val originalBill: Double,
    val requestAmount: Double,
    val status: PaymentStatus,
    val requestDate: String,
    val decisionDate: String? = null,
    val createdAt: Long = System.currentTimeMillis()
)

data class KhataNotification(
    val id: String,
    val recipientUid: String = "",
    val shopId: String? = null,
    val shopName: String? = null,
    val customerId: String? = null,
    val targetRole: UserRole,
    val title: String,
    val message: String,
    val date: String,
    val isRead: Boolean = false,
    val type: String = "GENERAL",
    val createdAt: Long = System.currentTimeMillis()
) {
    val targetApp: UserRole get() = targetRole
}

data class CustomerBalanceSummary(
    val currentMonthTotal: Double,
    val previousBalance: Double,
    val totalPayable: Double,
    val currentMonthLabel: String,
    val previousMonthLabel: String? = null,
    val previousOriginalBill: Double = 0.0,
    val previousPaidAmount: Double = 0.0
)

data class ConnectedShopKhataSummary(
    val connection: ConnectedKhata,
    val summary: CustomerBalanceSummary
)
